### ISSUE TITLE
Exclude root path

### ISSUE THREAD

**Issue by nicolasrouanne** [dmetivier/gatsby-plugin-page-progress#15]
**Is your feature request related to a problem? Please describe.**
I have a blog with:
- the root path being the list of posts `https://myblog.com/`
- a post path being immediately the post slug e.g. `https://myblog.com/awesome-post-about-gatsby`

**Describe the solution you'd like**
Some sort of config variable in `gatsby-config.js` with a list of paths to exclude **working for the root path**. Possibly accepting regexs
```js
excludePaths: ['/', '/about']
```

**Comment by dmetivier** [comment]
Seems simple enough. I'll find some time to work on this today.

## Requirements
- [ ] `excludePaths` must include the full relative path - `/beep/beep/lettuce`
> Will test out supplying regex to `excludePaths`. Above requirement will change if it works out.

Reason being that the current API accounts for leading slash in `matchStartOfPath` for less redundancy. Maybe in a future major version we can require `matchStartOfPath` to include the leading slash to make the API more consistent.

- [ ] `excludePaths` should also work with `matchStartOfPath` & `matchEndOfPath`

If we are including all paths that start with `/docs`, we would want the dexterity to explicitly exclude `/docs/method/caveats` from having a progress indicator.

**Comment by nicolasrouanne** [comment]
I guess you could also replace alltogether the `matchStartOfPath` and `matchEndOfPath` with ˋincludePath` and ˋexcludePath` taking both _String_ or _RegEx_. One of those would take precedence in case of rules matching boths.

I have a feeling it would allow much more granularity in the rules.

> this could even be in a minor version if you were to keep previous settings param and deprecate them. 

Just a suggestion though about the design of your module 😉

**Comment by dmetivier** [comment]
I was thinking about that because I'm gonna run into an annoying conditional issue when faced with:

> if theres an `excludePaths` match, and `matchStartOfPath.length` or `matchEndOfPath.length`

Which is an invalid expression...

I really didn't wanna release a v2 right away but ¯\_(ツ)_/¯ can't really argue just having the two makes a lot more sense. In the end I'll write less code. Thanks for the input! I'm gonna jump on this.

**Comment by dmetivier** [comment]
Would you mind doing a test run for me?

`npm i gatsby-plugin-page-progress@2.0.5-beta.1`

There's a bit of [new documentation](https://www.npmjs.com/package/gatsby-plugin-page-progress/v/2.0.5-beta.1) to get it going as well. I have to supply the regex as a string otherwise it gets lost in transit. Not really sure why, but that was the best way I could implement it for the time being.

Let me know what you think 🚀

**Comment by nicolasrouanne** [comment]
Sure! Will do tomorrow as I’m on holiday today 🏖
Thanks for making the changes so fast 🙌

**Comment by nicolasrouanne** [comment]
Seems to work great 🎉 
Have just tested a few cases they work fine 👌 Nice!

**Comment by dmetivier** [comment]
Great news! Changes have been merged. Latest version is available:

`npm i gatsby-plugin-page-progress@latest`
