### ISSUE TITLE
Dynamic Top Value

### ISSUE THREAD

**Issue by jyash97** [dmetivier/gatsby-plugin-page-progress#29]
**Is your feature request related to a problem? Please describe.**
Hey @dmetivier  
Awesome work on the plugin 💯 . I wanted to put the progress bar below my navbar which is also a fixed position. And there is currently no option provided for doing.

**Describe the solution you'd like**
Can we have an option for `top` ?

**Describe alternatives you've considered**
I had to apply styles using the `id` attribute. 

**Additional context**
If you think this is a good feature to support I can take a look at this.

**Comment by dmetivier** [comment]
@jyash97 Thank you for the kind words!

This enhancement sounds like it would support a niche. I would assume that your navbar is always fixed to the top and never changes height in any way. This sounds like it would be better served expediting that functionality to CSS rather than be added as a parameter to the plugin.

Someone made a suggestion on this before: #18 => PR: #20 

Have a look at this suggestion and PR and let me know what you think about this solution. If you like it I think it would make sense to implement that change and then go about changing things with CSS.

**Comment by jyash97** [comment]
Hey @dmetivier  

After reading through the comments. I think it does make sense to change property using CSS instead of adding a parameter to the plugin.

We can close this issue for now and if other users face this issue we can think of a solution.

Thanks 👍
